//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        public string MACAUHOI { get; set; }
        public string MADM { get; set; }
        public string CAUHOI1 { get; set; }
        public string NOIDUNCAUHOI { get; set; }
    
        public virtual DANHMUC_KHIEUNAY DANHMUC_KHIEUNAY { get; set; }
    }
}
