//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Web_CinemaManagement.Helper;

    public partial class QL_RAP_PHIMEntities : DbContext
    {
        public QL_RAP_PHIMEntities()
            : base(ConnectionHelper.getEFConnectionString(DataGlobal.UserID, DataGlobal.Password))
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<CAUHOI> CAUHOIs { get; set; }
        public virtual DbSet<CT_GHE_PHONG> CT_GHE_PHONG { get; set; }
        public virtual DbSet<DANGKY> DANGKies { get; set; }
        public virtual DbSet<DANGPHIM> DANGPHIMs { get; set; }
        public virtual DbSet<DANHMUC_KHIEUNAY> DANHMUC_KHIEUNAY { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<GHE> GHEs { get; set; }
        public virtual DbSet<HANGTHANHVIEN> HANGTHANHVIENs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIVE> LOAIVEs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NOIDUNG_PHANHOI> NOIDUNG_PHANHOI { get; set; }
        public virtual DbSet<PHIM> PHIMs { get; set; }
        public virtual DbSet<PHONGCHIEU> PHONGCHIEUx { get; set; }
        public virtual DbSet<SUATCHIEU> SUATCHIEUx { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THELOAIPHIM> THELOAIPHIMs { get; set; }
        public virtual DbSet<VE> VEs { get; set; }
        public virtual DbSet<YEUCAUHOTRO> YEUCAUHOTROes { get; set; }

        [DbFunction("QL_RAP_PHIMEntities", "fn_SuatChieuHomNay")]
        public virtual IQueryable<fn_SuatChieuHomNay_Result> fn_SuatChieuHomNay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SuatChieuHomNay_Result>("[QL_RAP_PHIMEntities].[fn_SuatChieuHomNay]()");
        }

        [DbFunction("QL_RAP_PHIMEntities", "LayPhimTheoThoiLuong")]
        public virtual IQueryable<LayPhimTheoThoiLuong_Result> LayPhimTheoThoiLuong(Nullable<int> opt)
        {
            var optParameter = opt.HasValue ?
                new ObjectParameter("opt", opt) :
                new ObjectParameter("opt", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LayPhimTheoThoiLuong_Result>("[QL_RAP_PHIMEntities].[LayPhimTheoThoiLuong](@opt)", optParameter);
        }

        [DbFunction("QL_RAP_PHIMEntities", "LaySuatChieu")]
        public virtual IQueryable<LaySuatChieu_Result> LaySuatChieu(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));

            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LaySuatChieu_Result>("[QL_RAP_PHIMEntities].[LaySuatChieu](@Ngay)", ngayParameter);
        }

        public virtual int PROC_DUYET_PHIM_SAP_CHIEU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DUYET_PHIM_SAP_CHIEU");
        }

        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));

            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));

            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));

            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }

        public virtual int SP_CHANGE_PASSWORD(string uSERID, string nEWPASS)
        {
            var uSERIDParameter = uSERID != null ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(string));

            var nEWPASSParameter = nEWPASS != null ?
                new ObjectParameter("NEWPASS", nEWPASS) :
                new ObjectParameter("NEWPASS", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHANGE_PASSWORD", uSERIDParameter, nEWPASSParameter);
        }

        public virtual int sp_CountDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CountDichVu");
        }

        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));

            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));

            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));

            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }

        public virtual int SP_DEMSOSP(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DEMSOSP", mASPParameter);
        }

        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));

            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }

        public virtual ObjectResult<SP_DS_NHANVIEN_Result> SP_DS_NHANVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DS_NHANVIEN_Result>("SP_DS_NHANVIEN");
        }

        public virtual ObjectResult<SP_DSSP_NHIEUNHAT_Result> SP_DSSP_NHIEUNHAT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DSSP_NHIEUNHAT_Result>("SP_DSSP_NHIEUNHAT");
        }

        public virtual ObjectResult<sp_GetAllLoaiVe_Result> sp_GetAllLoaiVe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllLoaiVe_Result>("sp_GetAllLoaiVe");
        }

        public virtual int sp_GetGiaVeByMaLoaiVe(string maLoaiVe, ObjectParameter giaVe)
        {
            var maLoaiVeParameter = maLoaiVe != null ?
                new ObjectParameter("MaLoaiVe", maLoaiVe) :
                new ObjectParameter("MaLoaiVe", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetGiaVeByMaLoaiVe", maLoaiVeParameter, giaVe);
        }

        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));

            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }

        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));

            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }

        public virtual int SP_LIETKETDANGPHIM(string mADP, ObjectParameter dANGPHIM)
        {
            var mADPParameter = mADP != null ?
                new ObjectParameter("MADP", mADP) :
                new ObjectParameter("MADP", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LIETKETDANGPHIM", mADPParameter, dANGPHIM);
        }

        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));

            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));

            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }

        public virtual ObjectResult<SP_SOLUONGPHIM_THELOAI_Result> SP_SOLUONGPHIM_THELOAI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SOLUONGPHIM_THELOAI_Result>("SP_SOLUONGPHIM_THELOAI");
        }

        public virtual int SP_TENKH_THEOMA(string mAKH, ObjectParameter hOTENKH)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TENKH_THEOMA", mAKHParameter, hOTENKH);
        }

        public virtual ObjectResult<SP_THELOAIPHIM_Result> SP_THELOAIPHIM(string mATHELOAI)
        {
            var mATHELOAIParameter = mATHELOAI != null ?
                new ObjectParameter("MATHELOAI", mATHELOAI) :
                new ObjectParameter("MATHELOAI", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THELOAIPHIM_Result>("SP_THELOAIPHIM", mATHELOAIParameter);
        }

        public virtual int SP_THEMDANGPHIM(string mADP, string dANGPHIM)
        {
            var mADPParameter = mADP != null ?
                new ObjectParameter("MADP", mADP) :
                new ObjectParameter("MADP", typeof(string));

            var dANGPHIMParameter = dANGPHIM != null ?
                new ObjectParameter("DANGPHIM", dANGPHIM) :
                new ObjectParameter("DANGPHIM", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMDANGPHIM", mADPParameter, dANGPHIMParameter);
        }

        public virtual int SP_THEMGHE(string mAGHE, Nullable<int> sOGHE, string lOAIGHE, string mAPHONG)
        {
            var mAGHEParameter = mAGHE != null ?
                new ObjectParameter("MAGHE", mAGHE) :
                new ObjectParameter("MAGHE", typeof(string));

            var sOGHEParameter = sOGHE.HasValue ?
                new ObjectParameter("SOGHE", sOGHE) :
                new ObjectParameter("SOGHE", typeof(int));

            var lOAIGHEParameter = lOAIGHE != null ?
                new ObjectParameter("LOAIGHE", lOAIGHE) :
                new ObjectParameter("LOAIGHE", typeof(string));

            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMGHE", mAGHEParameter, sOGHEParameter, lOAIGHEParameter, mAPHONGParameter);
        }

        public virtual int SP_THEMPHIMMOI(string mAPHIM, string mATHELOAI, string tENPHIM, string mADP, string nHASX, Nullable<System.DateTime> nGAYKHOICHIEU, Nullable<System.DateTime> nGAYKETTHUC, Nullable<System.TimeSpan> tHOILUONG)
        {
            var mAPHIMParameter = mAPHIM != null ?
                new ObjectParameter("MAPHIM", mAPHIM) :
                new ObjectParameter("MAPHIM", typeof(string));

            var mATHELOAIParameter = mATHELOAI != null ?
                new ObjectParameter("MATHELOAI", mATHELOAI) :
                new ObjectParameter("MATHELOAI", typeof(string));

            var tENPHIMParameter = tENPHIM != null ?
                new ObjectParameter("TENPHIM", tENPHIM) :
                new ObjectParameter("TENPHIM", typeof(string));

            var mADPParameter = mADP != null ?
                new ObjectParameter("MADP", mADP) :
                new ObjectParameter("MADP", typeof(string));

            var nHASXParameter = nHASX != null ?
                new ObjectParameter("NHASX", nHASX) :
                new ObjectParameter("NHASX", typeof(string));

            var nGAYKHOICHIEUParameter = nGAYKHOICHIEU.HasValue ?
                new ObjectParameter("NGAYKHOICHIEU", nGAYKHOICHIEU) :
                new ObjectParameter("NGAYKHOICHIEU", typeof(System.DateTime));

            var nGAYKETTHUCParameter = nGAYKETTHUC.HasValue ?
                new ObjectParameter("NGAYKETTHUC", nGAYKETTHUC) :
                new ObjectParameter("NGAYKETTHUC", typeof(System.DateTime));

            var tHOILUONGParameter = tHOILUONG.HasValue ?
                new ObjectParameter("THOILUONG", tHOILUONG) :
                new ObjectParameter("THOILUONG", typeof(System.TimeSpan));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMPHIMMOI", mAPHIMParameter, mATHELOAIParameter, tENPHIMParameter, mADPParameter, nHASXParameter, nGAYKHOICHIEUParameter, nGAYKETTHUCParameter, tHOILUONGParameter);
        }

        public virtual int SP_THEMPHONGCHIEU(string mAPHONG, string tENPHONG, Nullable<int> tONGSOGHE)
        {
            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));

            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));

            var tONGSOGHEParameter = tONGSOGHE.HasValue ?
                new ObjectParameter("TONGSOGHE", tONGSOGHE) :
                new ObjectParameter("TONGSOGHE", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMPHONGCHIEU", mAPHONGParameter, tENPHONGParameter, tONGSOGHEParameter);
        }

        public virtual int SP_THEMSUATCHIEU(string mASUAT, string mAPHONG, string mAPHIM, Nullable<System.TimeSpan> gIOBATDAU, Nullable<System.TimeSpan> gIOKETTHUC, Nullable<System.DateTime> nGAYCHIEU)
        {
            var mASUATParameter = mASUAT != null ?
                new ObjectParameter("MASUAT", mASUAT) :
                new ObjectParameter("MASUAT", typeof(string));

            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));

            var mAPHIMParameter = mAPHIM != null ?
                new ObjectParameter("MAPHIM", mAPHIM) :
                new ObjectParameter("MAPHIM", typeof(string));

            var gIOBATDAUParameter = gIOBATDAU.HasValue ?
                new ObjectParameter("GIOBATDAU", gIOBATDAU) :
                new ObjectParameter("GIOBATDAU", typeof(System.TimeSpan));

            var gIOKETTHUCParameter = gIOKETTHUC.HasValue ?
                new ObjectParameter("GIOKETTHUC", gIOKETTHUC) :
                new ObjectParameter("GIOKETTHUC", typeof(System.TimeSpan));

            var nGAYCHIEUParameter = nGAYCHIEU.HasValue ?
                new ObjectParameter("NGAYCHIEU", nGAYCHIEU) :
                new ObjectParameter("NGAYCHIEU", typeof(System.DateTime));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMSUATCHIEU", mASUATParameter, mAPHONGParameter, mAPHIMParameter, gIOBATDAUParameter, gIOKETTHUCParameter, nGAYCHIEUParameter);
        }

        public virtual int SP_THEMTHELOAIPHIM(string mATHELOAI, string tENTHELOAI)
        {
            var mATHELOAIParameter = mATHELOAI != null ?
                new ObjectParameter("MATHELOAI", mATHELOAI) :
                new ObjectParameter("MATHELOAI", typeof(string));

            var tENTHELOAIParameter = tENTHELOAI != null ?
                new ObjectParameter("TENTHELOAI", tENTHELOAI) :
                new ObjectParameter("TENTHELOAI", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMTHELOAIPHIM", mATHELOAIParameter, tENTHELOAIParameter);
        }

        public virtual int sp_ThongKeGhe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKeGhe");
        }

        public virtual int sp_ThongKePhongChieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKePhongChieu");
        }

        public virtual int sp_ThongKeSuatChieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKeSuatChieu");
        }

        public virtual ObjectResult<SP_THONGTINVE_Result> SP_THONGTINVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGTINVE_Result>("SP_THONGTINVE");
        }

        public virtual int SP_TONGSOVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TONGSOVE");
        }

        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
