//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_GHE_PHONG
    {
        public string MAGHE { get; set; }
        public string MAPHONG { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual GHE GHE { get; set; }
        public virtual PHONGCHIEU PHONGCHIEU { get; set; }
    }
}
