//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUC_KHIEUNAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHMUC_KHIEUNAY()
        {
            this.CAUHOIs = new HashSet<CAUHOI>();
            this.YEUCAUHOTROes = new HashSet<YEUCAUHOTRO>();
        }
    
        public string MADM { get; set; }
        public string TENDANHMUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAUHOI> CAUHOIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUCAUHOTRO> YEUCAUHOTROes { get; set; }
    }
}
