//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.NOIDUNG_PHANHOI = new HashSet<NOIDUNG_PHANHOI>();
            this.VEs = new HashSet<VE>();
            this.YEUCAUHOTROes = new HashSet<YEUCAUHOTRO>();
        }

        [Display(Name  = "Mã khách hàng")]
        public string MAKH { get; set; }

        [Display(Name = "Mã hạng thành viên")]
        public string MAHANG { get; set; }

        [Display(Name = "Họ tên khách hàng")]

        [Required(ErrorMessage = "{0} không được để trống")]

        public string HOTENKH { get; set; }

        [Display(Name = "Số điện thoại")]

        [Required(ErrorMessage = "{0} không được để trống")]

        public string SDT { get; set; }

        [Display(Name = "Địa chỉ")]

        [Required(ErrorMessage = "{0} không được để trống")]

        public string DIACHI { get; set; }

        [Display(Name = "Ngày sinh")]

        [Required(ErrorMessage = "{0} không được để trống")]

        public Nullable<System.DateTime> NGAYSINH { get; set; }

        [Display(Name = "Email")]

        [Required(ErrorMessage = "{0} không được để trống")]

        public string EMAIL { get; set; }

        [Display(Name = "Hình ảnh")]

        public string HINH_ANH { get; set; }

        [Display(Name = "Giới tính")]

        [Required(ErrorMessage = "{0} không được để trống")]

        public string PHAI { get; set; }
    
        public virtual HANGTHANHVIEN HANGTHANHVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIDUNG_PHANHOI> NOIDUNG_PHANHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUCAUHOTRO> YEUCAUHOTROes { get; set; }
    }
}
