//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.NOIDUNG_PHANHOI = new HashSet<NOIDUNG_PHANHOI>();
            this.VEs = new HashSet<VE>();
            this.YEUCAUHOTROes = new HashSet<YEUCAUHOTRO>();
        }
    
        public string MANV { get; set; }
        public string HOTENNV { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string PHAI { get; set; }
        public Nullable<decimal> LUONG { get; set; }
        public string CATRUC { get; set; }
        public string EMAIL { get; set; }
        public string HINH_ANH { get; set; }
        public string CHUCVU { get; set; }
        public string MA_NQL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIDUNG_PHANHOI> NOIDUNG_PHANHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUCAUHOTRO> YEUCAUHOTROes { get; set; }
    }
}
