//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOIDUNG_PHANHOI
    {
        public string MAND { get; set; }
        public string MAYEUCAU { get; set; }
        public string MAKH { get; set; }
        public string MANV { get; set; }
        public string NOIDUNG_PHANHOI1 { get; set; }
        public Nullable<System.DateTime> NGAYGUI_PHANHOI { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual YEUCAUHOTRO YEUCAUHOTRO { get; set; }
    }
}
