//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIM()
        {
            this.SUATCHIEUx = new HashSet<SUATCHIEU>();
        }
    
        public string MAPHIM { get; set; }
        public string MATHELOAI { get; set; }
        public string MADP { get; set; }
        public string TENPHIM { get; set; }
        public string NHASX { get; set; }
        public Nullable<System.DateTime> NGAYKHOICHIEU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<System.TimeSpan> THOILUONG { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string HINH_ANH { get; set; }
    
        public virtual DANGPHIM DANGPHIM { get; set; }
        public virtual THELOAIPHIM THELOAIPHIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUATCHIEU> SUATCHIEUx { get; set; }
    }
}
