//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUATCHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUATCHIEU()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public string MASUAT { get; set; }
        public string MAPHONG { get; set; }
        public string MAPHIM { get; set; }
        public System.TimeSpan GIOBATDAU { get; set; }
        public Nullable<System.TimeSpan> GIOKETTHUC { get; set; }
        public Nullable<System.DateTime> NGAYCHIEU { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        public virtual PHONGCHIEU PHONGCHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
    }
}
