//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VE()
        {
            this.DANGKies = new HashSet<DANGKY>();
        }
    
        public string MAVE { get; set; }
        public string MASUAT { get; set; }
        public string MALV { get; set; }
        public string MAKH { get; set; }
        public string MANV { get; set; }
        public string MAGHE { get; set; }
        public System.DateTime NGAYBANVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKY> DANGKies { get; set; }
        public virtual GHE GHE { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SUATCHIEU SUATCHIEU { get; set; }
    }
}
