//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CinemaManagement.Models.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEUCAUHOTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YEUCAUHOTRO()
        {
            this.NOIDUNG_PHANHOI = new HashSet<NOIDUNG_PHANHOI>();
        }
    
        public string MAYEUCAU { get; set; }
        public string MAKH { get; set; }
        public string MADM { get; set; }
        public string MANV { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string MUCDO_UUTIEN { get; set; }
        public Nullable<System.DateTime> NGAYTAOYEUCAU { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
    
        public virtual DANHMUC_KHIEUNAY DANHMUC_KHIEUNAY { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOIDUNG_PHANHOI> NOIDUNG_PHANHOI { get; set; }
    }
}
